<rosparam param="[sensor]_config">[x_pos,     y_pos,      z_pos,
                                   roll,      pitch,      yaw,
                                   x_vel,     y_vel,      z_vel,
                                   roll_rate, pitch_rate, yaw_rate,
                                   x_accel,   y_accel,    z_accel]</rosparam>